service: crud-dynamodb-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  createData:
    handler: functions/create.handler
    events:
      - http:
          path: create
          method: POST
  getData:
    handler: functions/getData.handler
    events:
      - http:
          path: get
          method: POST
  getAllDataByPk:
    handler: functions/getAllDataByPk.handler
    events:
      - http:
          path: query
          method: POST
  getAllData:
    handler: functions/getAllData.handler
    events:
      - http:
          path: scan
          method: POST
  deleteData:
    handler: functions/deleteData.handler
    events:
      - http:
          path: delete
          method: POST
