service: crud-dynamodb-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  createData:
    handler: functions/create.handler
    events:
      - http:
          path: create
          method: POST
  getAllDataByPk:
    handler: functions/getAllDataByPk.handler
    events:
      - http:
          path: getAllDataByPk
          method: POST
