service: crud-dynamodb-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:UpdateItem
            - dynamodb:BatchGetItem
            - dynamodb:BatchWriteItem
          Resource:
            - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/studentData"

functions:
  createData:
    handler: functions/create.handler
    events:
      - http:
          path: create
          method: POST
  getData:
    handler: functions/getData.handler
    events:
      - http:
          path: get
          method: POST
  getAllDataByPk:
    handler: functions/getAllDataByPk.handler
    events:
      - http:
          path: query
          method: POST
  getAllData:
    handler: functions/getAllData.handler
    events:
      - http:
          path: scan
          method: POST
  updateData:
    handler: functions/updateData.handler
    events:
      - http:
          path: update
          method: POST
  deleteData:
    handler: functions/deleteData.handler
    events:
      - http:
          path: delete
          method: POST
  batchWriteData:
    handler: functions/batchWriteData.handler
    events:
      - http:
          path: batchWrite
          method: POST
