service: crud-dynamodb-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  api:
    handler: index.handler
    events:
      - http:
          path: create
          method: POST
